buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ':'
siteStream:
  id: site-stream
  entityId: site
  fields:
    - name
  localization:
    locales:
      - en
responseHeaders:
  -
    pathPattern: .*
    headerKey: joe-custom-header
    headerValues:
      - joe-custom-value
