buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install && echo -e "\033[31;1;4mHello\033[0m" && echo -e "\033[1;mBold\033[0m" && npm bad
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: npm run dev -- --no-prod-url --local
