buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: npm run dev -- --no-prod-url --local

responseHeaders:
  -
    pathPattern: .*
    headerKey: aaron-custom-header
    headerValues:
      - custom-value    
