buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install && echo -e "\033[31;1;4mHello\033[0m"
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: npm run dev -- --no-prod-url --local
